spring:
  application:
    name: aiplayer-service
  data :
    mongodb:
      url : mongodb+srv://<username>:<password>@cluster0.mongodb.net?retryWrites=true
      database : interview_test
  jackson:
    date-format : yyyy-MM-dd
    serialization : 
      WRITE_DATES_AS_TIMESTAMPS : false

